// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/layout-variants/IconRail.tsx": () => import("../components/mockups/layout-variants/IconRail.tsx"),
  "./components/mockups/layout-variants/OverlayDrawer.tsx": () => import("../components/mockups/layout-variants/OverlayDrawer.tsx"),
  "./components/mockups/layout-variants/TopNav.tsx": () => import("../components/mockups/layout-variants/TopNav.tsx")
};
